import { Pipe } from '@common/types';
import { H0uncnt0Data } from '../types/h0uncnt0.types';

/**
 * 국내주식 실시간체결가 (통합/KRX/NXT)
 * 통합: H0UNCNT0
 * KRX: H0STCNT0
 * NXT: H0STCNT0
 *
 * @see https://apiportal.koreainvestment.com/apiservice-apiservice?/tryitout/H0UNCNT0
 */
export class TradeStreamPipe implements Pipe<string[], H0uncnt0Data> {
    public transform(value: string[]): H0uncnt0Data {
        const [
            MKSC_SHRN_ISCD,
            STCK_CNTG_HOUR,
            STCK_PRPR,
            PRDY_VRSS_SIGN,
            PRDY_VRSS,
            PRDY_CTRT,
            WGHN_AVRG_STCK_PRC,
            STCK_OPRC,
            STCK_HGPR,
            STCK_LWPR,
            ASKP1,
            BIDP1,
            CNTG_VOL,
            ACML_VOL,
            ACML_TR_PBMN,
            SELN_CNTG_CSNU,
            SHNU_CNTG_CSNU,
            NTBY_CNTG_CSNU,
            CTTR,
            SELN_CNTG_SMTN,
            SHNU_CNTG_SMTN,
            CNTG_CLS_CODE,
            SHNU_RATE,
            PRDY_VOL_VRSS_ACML_VOL_RATE,
            OPRC_HOUR,
            OPRC_VRSS_PRPR_SIGN,
            OPRC_VRSS_PRPR,
            HGPR_HOUR,
            HGPR_VRSS_PRPR_SIGN,
            HGPR_VRSS_PRPR,
            LWPR_HOUR,
            LWPR_VRSS_PRPR_SIGN,
            LWPR_VRSS_PRPR,
            BSOP_DATE,
            NEW_MKOP_CLS_CODE,
            TRHT_YN,
            ASKP_RSQN1,
            BIDP_RSQN1,
            TOTAL_ASKP_RSQN,
            TOTAL_BIDP_RSQN,
            VOL_TNRT,
            PRDY_SMNS_HOUR_ACML_VOL,
            PRDY_SMNS_HOUR_ACML_VOL_RATE,
            HOUR_CLS_CODE,
            MRKT_TRTM_CLS_CODE,
            VI_STND_PRC,
        ] = value;

        return {
            MKSC_SHRN_ISCD,
            STCK_CNTG_HOUR,
            STCK_PRPR,
            PRDY_VRSS_SIGN,
            PRDY_VRSS,
            PRDY_CTRT,
            WGHN_AVRG_STCK_PRC,
            STCK_OPRC,
            STCK_HGPR,
            STCK_LWPR,
            ASKP1,
            BIDP1,
            CNTG_VOL,
            ACML_VOL,
            ACML_TR_PBMN,
            SELN_CNTG_CSNU,
            SHNU_CNTG_CSNU,
            NTBY_CNTG_CSNU,
            CTTR,
            SELN_CNTG_SMTN,
            SHNU_CNTG_SMTN,
            CNTG_CLS_CODE,
            SHNU_RATE,
            PRDY_VOL_VRSS_ACML_VOL_RATE,
            OPRC_HOUR,
            OPRC_VRSS_PRPR_SIGN,
            OPRC_VRSS_PRPR,
            HGPR_HOUR,
            HGPR_VRSS_PRPR_SIGN,
            HGPR_VRSS_PRPR,
            LWPR_HOUR,
            LWPR_VRSS_PRPR_SIGN,
            LWPR_VRSS_PRPR,
            BSOP_DATE,
            NEW_MKOP_CLS_CODE,
            TRHT_YN,
            ASKP_RSQN1,
            BIDP_RSQN1,
            TOTAL_ASKP_RSQN,
            TOTAL_BIDP_RSQN,
            VOL_TNRT,
            PRDY_SMNS_HOUR_ACML_VOL,
            PRDY_SMNS_HOUR_ACML_VOL_RATE,
            HOUR_CLS_CODE,
            MRKT_TRTM_CLS_CODE,
            VI_STND_PRC,
        };
    }
}
